/**
 * Test Script for Reports Database Storage
 * 
 * This script tests that reports are being saved correctly.
 * Run this AFTER starting the backend server.
 */

const axios = require('axios');

// Configuration - UPDATE THESE VALUES
const BASE_URL = 'http://localhost:3001/api';
const ADMIN_TOKEN = 'YOUR_ADMIN_TOKEN_HERE'; // Replace with actual token

// Helper function to make authenticated requests
const api = axios.create({
  baseURL: BASE_URL,
  headers: {
    'Authorization': `Bearer ${ADMIN_TOKEN}`,
  },
});

async function testReports() {
  console.log('🧪 Testing Reports Database Storage Implementation\n');
  
  try {
    // Test 1: Generate a report (this should save it to database)
    console.log('📝 Test 1: Generating batch attendance report...');
    const batchResponse = await api.get('/reports/batch-attendance', {
      params: { batchId: 1 }
    });
    console.log('✅ Report generated successfully');
    console.log(`   Total sessions: ${batchResponse.data.data.totalSessions}`);
    console.log(`   Total attendances: ${batchResponse.data.data.totalAttendances}\n`);

    // Test 2: Generate another report
    console.log('📝 Test 2: Generating pending payments report...');
    const paymentsResponse = await api.get('/reports/pending-payments');
    console.log('✅ Report generated successfully');
    console.log(`   Total pending: ${paymentsResponse.data.data.summary.totalPending}`);
    console.log(`   Total amount: ₹${paymentsResponse.data.data.summary.totalPendingAmount}\n`);

    // Test 3: Get all saved reports
    console.log('📝 Test 3: Fetching all saved reports...');
    const savedReportsResponse = await api.get('/reports/saved', {
      params: { page: 1, limit: 10 }
    });
    console.log('✅ Saved reports retrieved successfully');
    console.log(`   Total reports in database: ${savedReportsResponse.data.data.pagination.total}`);
    console.log(`   Reports on this page: ${savedReportsResponse.data.data.reports.length}\n`);

    // Display saved reports
    console.log('📊 Recent Saved Reports:');
    savedReportsResponse.data.data.reports.forEach((report, index) => {
      console.log(`   ${index + 1}. ${report.reportName}`);
      console.log(`      Type: ${report.reportType}`);
      console.log(`      Generated by: ${report.generator?.name || 'Unknown'}`);
      console.log(`      Records: ${report.recordCount || 'N/A'}`);
      console.log(`      Created: ${new Date(report.createdAt).toLocaleString()}\n`);
    });

    // Test 4: Get specific report details
    if (savedReportsResponse.data.data.reports.length > 0) {
      const firstReportId = savedReportsResponse.data.data.reports[0].id;
      console.log(`📝 Test 4: Fetching details of report #${firstReportId}...`);
      const reportDetailsResponse = await api.get(`/reports/saved/${firstReportId}`);
      console.log('✅ Report details retrieved successfully');
      console.log(`   Report Name: ${reportDetailsResponse.data.data.reportName}`);
      console.log(`   Status: ${reportDetailsResponse.data.data.status}`);
      console.log(`   Has Data: ${!!reportDetailsResponse.data.data.data}\n`);
    }

    // Test 5: Filter reports by type
    console.log('📝 Test 5: Filtering reports by type (pending-payments)...');
    const filteredResponse = await api.get('/reports/saved', {
      params: { reportType: 'pending-payments' }
    });
    console.log('✅ Filtered reports retrieved successfully');
    console.log(`   Found ${filteredResponse.data.data.pagination.total} pending payments reports\n`);

    console.log('✅ ALL TESTS PASSED!');
    console.log('\n✨ Summary:');
    console.log('   - Reports are being saved to database ✓');
    console.log('   - Reports can be retrieved ✓');
    console.log('   - Pagination works ✓');
    console.log('   - Filtering works ✓');
    console.log('   - Report details accessible ✓');

  } catch (error) {
    console.error('❌ TEST FAILED');
    if (error.response) {
      console.error(`Status: ${error.response.status}`);
      console.error(`Data:`, error.response.data);
    } else if (error.request) {
      console.error('No response received. Is the server running?');
    } else {
      console.error('Error:', error.message);
    }
  }
}

// Run the test
testReports();
